# Generated by Django 4.0.6 on 2022-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcetgory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcetgory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
