# Generated by Django 4.0.6 on 2022-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_modified_date_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'publish')], default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Enter Your Title Here', max_length=150),
        ),
    ]
